// <auto-generated />
using cloudscribe.Kvp.Storage.EFCore.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace cloudscribe.Kvp.Storage.EFCore.SQLite.Migrations
{
    [DbContext(typeof(KvpDbContext))]
    [Migration("20171221173106_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("cloudscribe.Kvp.Models.KvpItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Custom1")
                        .HasMaxLength(255);

                    b.Property<string>("Custom2")
                        .HasMaxLength(255);

                    b.Property<string>("FeatureId")
                        .HasMaxLength(36);

                    b.Property<string>("Key")
                        .HasMaxLength(255);

                    b.Property<DateTime>("ModifiedUtc");

                    b.Property<string>("SetId")
                        .HasMaxLength(36);

                    b.Property<string>("SubSetId")
                        .HasMaxLength(36);

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("Key");

                    b.HasIndex("SetId");

                    b.HasIndex("SubSetId");

                    b.ToTable("KvpItems");
                });
#pragma warning restore 612, 618
        }
    }
}
